[package]
name = "prng"
version = "0.0.3"
description = "Statistical pseudo-random number generators"
repository = "https://github.com/research-ag/prng"
keywords = [ "rand", "random", "rng", "sfc", "seiran" ]
license = "Apache-2.0"
