[package]
name = "cycles-simple"
version = "0.10.0"
description = "A library for topping child canister (such as CanDB partition canisters) cycles from a parent canister"
repository = "https://github.com/vporton/cycles-simple"
keywords = [ "cycles", "canisters", "topping", "sending" ]
license = "MIT"