[dependencies]
base = "0.11.1"
btree = "https://github.com/canscale/StableHeapBTreeMap#v0.3.1"
stable-rbtree = "https://github.com/canscale/StableRBTree#v0.6.1"
stable-buffer = "https://github.com/canscale/StableBuffer#v0.2.0"
matchers = "https://github.com/kritzcreek/motoko-matchers#3dac8a071b69e4e651b25a7d9683fe831eb7cffd"
prng = "https://github.com/research-ag/prng#main"
sha = "https://github.com/enzoh/motoko-sha#master"
stableheapbtreemap = "1.5.0"
sha2 = "0.0.5"